### ISSUE TITLE
Shouldn't panic on failure to connect to k8s

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-core#33]
```
panic: Post https://10.96.0.1:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp 10.96.0.1:443: connect: connection refused
goroutine 22 [running]:
github.com/nre-learning/syringe/scheduler.(*LessonScheduler).createNetworkCrd(0xc4204c12c0, 0x1386d40, 0xc420568360)
	/go/src/github.com/nre-learning/syringe/scheduler/networks.go:33 +0x94
github.com/nre-learning/syringe/scheduler.(*LessonScheduler).Start(0xc4204c12c0, 0x0, 0x0)
	/go/src/github.com/nre-learning/syringe/scheduler/scheduler.go:83 +0x3d
main.main.func2(0xc4204c12c0, 0xc42036aec0)
	/go/src/github.com/nre-learning/syringe/cmd/syringed/main.go:65 +0x2f
created by main.main
	/go/src/github.com/nre-learning/syringe/cmd/syringed/main.go:64 +0x538
```

**Comment by Mierdin** [comment]
This is an extremely old issue that's no longer relevant.
