### ISSUE TITLE
kubelab crashes

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-core#73]
```

10.38.0.38 - - [17/Feb/2019:18:22:41 +0000] "GET /exp/lessondef/17 HTTP/1.1" 200 4235
time="2019-02-17T18:22:41Z" level=debug msg="Scheduler received new request. Sending to handle function." Operation=3 Stage=2 Uuid=17-wxd1zqhqmej6qoiv
panic: runtime error: index out of range
goroutine 180539 [running]:
github.com/nre-learning/syringe/scheduler.(*KubeLab).ToLiveLesson(0xc420c6eae0, 0xc421310a20)
	/go/src/github.com/nre-learning/syringe/scheduler/kubelab.go:105 +0xb7f
github.com/nre-learning/syringe/scheduler.(*LessonScheduler).handleRequestMODIFY(0xc4201edc70, 0xc420b699c0)
	/go/src/github.com/nre-learning/syringe/scheduler/requests.go:176 +0x146
github.com/nre-learning/syringe/scheduler.(*LessonScheduler).(github.com/nre-learning/syringe/scheduler.handleRequestMODIFY)-fm(0xc420b699c0)
	/go/src/github.com/nre-learning/syringe/scheduler/scheduler.go:93 +0x34
github.com/nre-learning/syringe/scheduler.(*LessonScheduler).Start.func2(0xc4206d2810, 0xc420b699c0)
	/go/src/github.com/nre-learning/syringe/scheduler/scheduler.go:107 +0x6d
created by github.com/nre-learning/syringe/scheduler.(*LessonScheduler).Start
	/go/src/github.com/nre-learning/syringe/scheduler/scheduler.go:106 +0x3ff

```

**Comment by Mierdin** [comment]
I'll keep this open for now but I will mention that this doesn't seem to happen often at all, and whatever is causing this will also almost certainly be removed in https://github.com/nre-learning/proposals/pull/3 (we're killing off kubelab)
